export MY_TOP_PATH=/home/sonvhi/chenxiaosong/
export MY_CODE_TOP_PATH=${MY_TOP_PATH}/code/

# Get the aliases and functions
# if [ -f ~/.bashrc ]; then
#         . ~/.bashrc
# fi

qemu_path=${MY_TOP_PATH}/sw/qemu/bin/
crash_path=${MY_TOP_PATH}/code/crash
samba_path=/usr/local/samba/bin/:/usr/local/samba/sbin/

export PATH=${crash_path}:${qemu_path}:${samba_path}:$PATH

# 设置 terminal 标签名称， 用法: title tab name
# 只用于ubuntu默认的terminal，因为ubuntu默认的terminal无法通过鼠标来改标签标题
function title() {
	if [[ -z "$ORIG" ]]; then
		ORIG=$PS1
	fi
	TITLE="\[\e]2;$*\a\]"
	PS1=${ORIG}${TITLE}
}

stty -ixon # 搜索历史命令，ctrl + s不锁屏
source /usr/share/bash-completion/completions/git # docker中要先安装 apt install bash-completion -y
# 只显示最后一个路径名分量
PS1="${PS1//\\w\\$/\\W\\$}"

